### ISSUE TITLE
How to set enable the CORS for Webapps?

### ISSUE THREAD

**Issue by mayurpxp** [vmware/idm#12]
I'm using the angular **angular-oauth2-oidc-jwks** library. I have added AuthConfig but getting a cors issue for the token URL. We have configured the information in the identity server as well. 

If I enable my browsers cors plugin then I'm getting the token after sign in from workspace one. But I want this to be done without any cors plugin. 

So how to enable cors for my web apps inside VMware Identity Manager?

**Error**: _

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://XXXX.com/acs/token. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
> Error getting token

_

**Comment by fstrudel** [comment]
You would need to enable CORS on the VMware Identity Manager side, but though I think it's possible for the on-prem product, I don't think it's available for the hosted product.

**Comment by mayurpxp** [comment]
Yes this was the Identity manager side issue. Team enabled it and issue is resolved. Thanks you.

**Comment by ACorreia2112** [comment]
Is there anyway you could help we are having same issues. Vmware support not being to helpful. Anyway you can share your fix.

**Comment by ACorreia2112** [comment]
> Yes this was the Identity manager side issue. Team enabled it and issue is resolved. Thanks you.

Is there anyway you could help we are having same issues. Vmware support not being to helpful. Anyway you can share your fix.

**Comment by KalebJG** [comment]
@ACorreia2112 - were you ever able to solve this? I'm running into the same issue. How do you enable it?
