### ISSUE TITLE
Bug on filter

### ISSUE THREAD

**Issue by BenJaziaSadok** [vmware/idm#14]
https://github.com/vmware/idm/wiki/SCIM-guide#search-for-a-user-by-username-cuser123

Old value
GET /SAAS/jersey/manager/api/scim/Users?filter=userName%20eq%20%cuser123%22

New value
GET /SAAS/jersey/manager/api/scim/Users?filter=userName%20eq%20%22cuser123%22

**Comment by fstrudel** [comment]
Fixed, thanks for reporting!
