### ISSUE TITLE
resource owner password credentials grant flow supports?

### ISSUE THREAD

**Issue by seanhuxy** [vmware/idm#2]
Hi,

I am wondering if vmware idm supports the resource owner password flow. I am currently working on an application, where we want to login directly from a CLI, with idm as an external provider.

Thanks!

**Comment by fstrudel** [comment]
Hi,

Yes Sean we do support resource owner password flow. We do not recommend this option as this will limit you to username and password authentication only, not allowing you to use other types of authentication methods (like MFA, RSA SecurID, etc...)
We recommend using the OAuth2 authorization code flow instead with the loopback approach.
See an example of a CLI doing this to authenticate users: 
https://github.com/vmware/priam

(use -a option)

But let me know if you want further details on the resource owner password grant flow though.

Fanny

**Comment by seanhuxy** [comment]
Thank you Fanny, It looks like a very good example, I'll give it a shot.
