### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by samcontesse** [vmware/idm#8]
Hi !

We have integrated our webapp successfully (https://github.com/vmware/idm/wiki/Integrating-Webapp-with-OAuth2) but we are still lacking information how to perform a logout. Can anyone help here ? Many thanks !

**Comment by fstrudel** [comment]
Hello!
The sample application has a logout button: it will remove the user's session of the webapp, i.e. remove the cookies. SpringBoot has built-in support for that, it is configured when we do:
`.and().logout().logoutSuccessUrl("/")`

Note that this does not log you out from your Identity Provider (VMware Identity Manager), but only from your application.

Fanny

**Comment by samcontesse** [comment]
Hello Fanny,

Thank you for your quick reply. My question is more about how to log out from vIDM and avoid the same token to be reused.

**Comment by fstrudel** [comment]
Hello,
This is a different issue then. We don't recommend to log out from VIDM if you log out from your application unless you have a very good reason to do so.
The issue being that if you remove the user's session on VIDM (VMware Identity Manager), then you remove SSO for all the other apps federated to VIDM as well.
If you really need to log out from VIDM, you can redirect to <your VIDM URL>/SAAS/auth/logout

Hope that answers your question?
Fanny

**Comment by samcontesse** [comment]
Hello,

As strange as it sounds, we've been asked to perform a _SSO logout_ and `/SAAS/auth/logout` is what I was looking for.

Thank you so much !
